import PDFDocument from 'pdfkit';

const BRAND_TEAL = '#0D9488';
const BRAND_DARK = '#1E293B';
const LIGHT_GREY = '#F1F5F9';
const GREEN = '#16A34A';
const RED = '#DC2626';
const YELLOW = '#CA8A04';

/**
 * Generate a PDF compliance report and pipe it to a writable stream.
 */
export function generateReport(scanRow, stream) {
  const results = typeof scanRow.results_json === 'string'
    ? JSON.parse(scanRow.results_json)
    : scanRow.results_json;

  const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true });
  doc.pipe(stream);

  // ── Header ──────────────────────────────────────────────────────────────
  doc.rect(0, 0, doc.page.width, 80).fill(BRAND_TEAL);
  doc.fontSize(22).fillColor('#FFFFFF')
    .text('AI APPROVE — Compliance Monitoring Report', 50, 28, { align: 'left' });

  doc.moveDown(2);

  // ── Scan metadata ─────────────────────────────────────────────────────
  doc.fillColor(BRAND_DARK).fontSize(11);
  doc.text(`Scan Date: ${scanRow.created_at}`, 50);
  doc.text(`Target URL: ${scanRow.target_url}`);
  doc.text(`Domain: ${scanRow.domain}`);
  doc.moveDown(1);

  // ── Summary table ─────────────────────────────────────────────────────
  doc.fontSize(14).fillColor(BRAND_TEAL).text('Summary', 50);
  doc.moveDown(0.5);

  const summaryData = [
    ['Pages Scanned', String(scanRow.pages_scanned)],
    ['PI Links Found', String(scanRow.pi_links_found)],
    ['Pass', String(scanRow.pass)],
    ['Warnings', String(scanRow.warn)],
    ['Failures', String(scanRow.fail)],
    ['Scan Time', `${scanRow.scan_time_seconds}s`],
  ];

  const tableLeft = 50;
  const colWidths = [200, 150];
  let y = doc.y;

  // Header row
  doc.rect(tableLeft, y, colWidths[0] + colWidths[1], 22).fill(BRAND_TEAL);
  doc.fillColor('#FFFFFF').fontSize(10);
  doc.text('Metric', tableLeft + 8, y + 6, { width: colWidths[0] });
  doc.text('Value', tableLeft + colWidths[0] + 8, y + 6, { width: colWidths[1] });
  y += 22;

  for (let i = 0; i < summaryData.length; i++) {
    const [label, value] = summaryData[i];
    if (i % 2 === 0) doc.rect(tableLeft, y, colWidths[0] + colWidths[1], 20).fill(LIGHT_GREY);
    doc.fillColor(BRAND_DARK).fontSize(10);
    doc.text(label, tableLeft + 8, y + 5, { width: colWidths[0] });
    doc.text(value, tableLeft + colWidths[0] + 8, y + 5, { width: colWidths[1] });
    y += 20;
  }

  doc.y = y + 20;

  // ── Results table ─────────────────────────────────────────────────────
  doc.fontSize(14).fillColor(BRAND_TEAL).text('Detailed Results', 50);
  doc.moveDown(0.5);

  const rColWidths = [150, 200, 50, 95];
  const rTableWidth = rColWidths.reduce((a, b) => a + b, 0);
  y = doc.y;

  // Header
  doc.rect(tableLeft, y, rTableWidth, 22).fill(BRAND_TEAL);
  doc.fillColor('#FFFFFF').fontSize(9);
  let xOff = tableLeft + 5;
  ['Page', 'PI Link', 'Status', 'Issue'].forEach((h, i) => {
    doc.text(h, xOff, y + 6, { width: rColWidths[i] - 10 });
    xOff += rColWidths[i];
  });
  y += 22;

  // Rows
  let rowIdx = 0;
  for (const page of results) {
    if (page.pi_links.length === 0 && !page.missing_pi) continue;

    if (page.missing_pi) {
      y = drawResultRow(doc, y, tableLeft, rColWidths, rowIdx++, {
        page: page.page,
        link: '—',
        status: 'MISSING',
        statusColor: RED,
        issue: 'No PI on promotional page',
      });
    }

    for (const link of page.pi_links) {
      const statusColor = link.ok ? GREEN : RED;
      const statusText = link.ok ? 'PASS' : 'FAIL';
      y = drawResultRow(doc, y, tableLeft, rColWidths, rowIdx++, {
        page: page.page,
        link: truncate(link.text || link.url, 45),
        status: statusText,
        statusColor,
        issue: link.issue || '—',
      });
    }
  }

  // ── Footer on every page ──────────────────────────────────────────────
  const pageCount = doc.bufferedPageRange().count;
  for (let i = 0; i < pageCount; i++) {
    doc.switchToPage(i);
    doc.fontSize(8).fillColor('#94A3B8')
      .text('Generated by AI Approve Compliance Monitoring — aiapprove.io',
        50, doc.page.height - 40, { align: 'center', width: doc.page.width - 100 });
  }

  doc.end();
}

function drawResultRow(doc, y, left, colWidths, idx, data) {
  const rowHeight = 18;

  // New page if we're near the bottom
  if (y + rowHeight > doc.page.height - 60) {
    doc.addPage();
    y = 50;
  }

  const totalW = colWidths.reduce((a, b) => a + b, 0);
  if (idx % 2 === 0) doc.rect(left, y, totalW, rowHeight).fill(LIGHT_GREY);

  doc.fontSize(8).fillColor(BRAND_DARK);
  let x = left + 5;
  doc.text(truncate(data.page, 35), x, y + 4, { width: colWidths[0] - 10 });
  x += colWidths[0];
  doc.text(data.link, x, y + 4, { width: colWidths[1] - 10 });
  x += colWidths[1];
  doc.fillColor(data.statusColor).text(data.status, x, y + 4, { width: colWidths[2] - 10 });
  x += colWidths[2];
  doc.fillColor(BRAND_DARK).text(truncate(data.issue, 25), x, y + 4, { width: colWidths[3] - 10 });

  return y + rowHeight;
}

function truncate(str, max) {
  if (!str) return '—';
  return str.length > max ? str.slice(0, max - 1) + '…' : str;
}
